'use client';import{useState,useRef,useEffect}from'react';import{authApi}from'@/lib/api';

interface LP{onClose?:()=>void;onSuccess?:()=>void;title?:string}
export default function LoginModal({onClose,onSuccess,title}:LP){
const[s,ss]=useState<'phone'|'otp'>('phone');const[ph,sph]=useState('');const[cd,scd]=useState('');const[er,ser]=useState('');const[ld,sld]=useState(false);const[timer,stimer]=useState(0);const ti=useRef<any>(null);
const sendOtp=async()=>{if(!/^09\d{9}$/.test(ph.replace(/\s/g,''))){ser('شماره موبایل معتبر وارد کنید (۰۹XXXXXXXXX)');return}ser('');sld(true);try{await authApi.sendOTP(ph);ss('otp');stimer(120);ti.current=setInterval(()=>{stimer(p=>{if(p<=1){clearInterval(ti.current);return 0}return p-1})},1000)}catch(x:any){ser(x?.response?.data?.message||'ارسال کد ناموفق بود')}finally{sld(false)}};
const verify=async()=>{if(cd.length<4){ser('کد را کامل وارد کنید');return}ser('');sld(true);try{await authApi.login(ph,cd);clearInterval(ti.current);onSuccess?.();onClose?.()}catch(x:any){ser(x?.response?.data?.message||'کد نادرست است')}finally{sld(false)}};
useEffect(()=>()=>{if(ti.current)clearInterval(ti.current)},[]);
return<div onClick={onClose} style={O}><div onClick={e=>e.stopPropagation()} style={M}><style>{`@keyframes modalIn{from{opacity:0;transform:translateY(20px) scale(.96)}to{opacity:1;transform:translateY(0) scale(1)}}`}</style>
<div style={H}><div style={{width:48,height:48,borderRadius:'50%',background:'linear-gradient(135deg,var(--brand-gold),var(--brand-gold-light))',display:'flex',alignItems:'center',justifyContent:'center',margin:'0 auto 16px',boxShadow:'0 0 32px rgba(198,169,98,.25)'}}><svg width="22" height="22" viewBox="0 0 24 24" fill="#0a0a0a"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg></div><h2 style={{textAlign:'center',fontSize:'1.3rem',fontWeight:800,marginBottom:4}}>{title||'ورود به آین تراز'}</h2><p style={{textAlign:'center',fontSize:'0.8125rem',color:'var(--text-muted)',marginBottom:24}}>{s==='phone'?'با شماره موبایل وارد شوید':'کد ارسال شده را وارد کنید'}</p></div>
{er&&<div style={{background:'rgba(239,68,68,.1)',border:'1px solid rgba(239,68,68,.3)',borderRadius:'var(--radius-sm)',padding:'10px 14px',fontSize:'0.8125rem',color:'#ef4444',marginBottom:16}}>{er}</div>}
{s==='phone'?<><input value={ph} onChange={e=>sph(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendOtp()} placeholder="09XXXXXXXXX" dir="ltr" style={{...I,textAlign:'center',letterSpacing:'0.02em'}} autoFocus/><button onClick={sendOtp} disabled={ld} className="btn btn-primary" style={{width:'100%',marginTop:12}}>{ld?'در حال ارسال...':'ارسال کد ورود'}</button></>:<><div style={{display:'flex',gap:8,justifyContent:'center',marginBottom:12}}><input value={cd} onChange={e=>scd(e.target.value.replace(/\D/g,'').slice(0,6))} onKeyDown={e=>e.key==='Enter'&&verify()} placeholder="------" dir="ltr" style={{...I,textAlign:'center',letterSpacing:'0.5em',fontSize:'1.25rem',fontWeight:700,maxWidth:200}} autoFocus/></div>{timer>0?<p style={{textAlign:'center',fontSize:'0.8125rem',color:'var(--text-muted)',marginBottom:12}}>{Math.floor(timer/60)}:{String(timer%60).padStart(2,'0')} تا ارسال مجدد</p>:<button onClick={sendOtp} style={{background:'none',border:'none',color:'var(--brand-gold)',cursor:'pointer',fontFamily:'Vazirmatn',fontSize:'0.8125rem',display:'block',margin:'0 auto 12px'}}>ارسال مجدد کد</button>}<button onClick={verify} disabled={ld} className="btn btn-primary" style={{width:'100%'}}>{ld?'در حال بررسی...':'تأیید و ورود'}</button><button onClick={()=>{ss('phone');scd('');ser('')}} style={{background:'none',border:'none',color:'var(--text-muted)',cursor:'pointer',fontFamily:'Vazirmatn',fontSize:'0.8125rem',display:'block',margin:'12px auto 0'}}>← تغییر شماره</button></>}
</div></div>;}
const O:React.CSSProperties={position:'fixed',inset:0,background:'rgba(0,0,0,.7)',backdropFilter:'blur(8px)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:1000,padding:20};
const M:React.CSSProperties={background:'var(--surface-card)',border:'1px solid var(--border-subtle)',borderRadius:'var(--radius-lg)',padding:32,maxWidth:380,width:'100%',animation:'modalIn .3s var(--ease-expo)'};
const I:React.CSSProperties={width:'100%',padding:'14px 18px',background:'rgba(255,255,255,.04)',border:'1.5px solid var(--border-subtle)',borderRadius:'var(--radius-md)',color:'var(--text-primary)',fontFamily:'Vazirmatn,sans-serif',fontSize:'.9375rem',outline:'none'};
const H:React.CSSProperties={marginBottom:8};
