'use client';
import { useState, useEffect, useRef, useCallback } from 'react';
import Link from 'next/link';
import { adminApi } from '@/lib/api';
import type { DashboardStats, RecentActivity, UserRow, AuditLog, PaginatedResponse } from '@/types';

type Tab='dashboard'|'users'|'content'|'audit';

export default function AdminPage(){
  const[tab,setTab]=useState<Tab>('dashboard');
  const[stats,setStats]=useState<DashboardStats|null>(null);
  const[act,setAct]=useState<RecentActivity|null>(null);
  const[users,setUsers]=useState<PaginatedResponse<UserRow>|null>(null);
  const[logs,setLogs]=useState<PaginatedResponse<AuditLog>|null>(null);
  const[load,setLoad]=useState(true);
  const[up,setUp]=useState(1);const[ap,setAp]=useState(1);
  const[q,setQ]=useState('');
  const[toast,setToast]=useState('');
  const[txts,setTxts]=useState<Record<string,string>>({hero:'راهکارهای هوشمند مالیاتی',sub:'با آیان تراز، پیچیدگی‌های مالیاتی را به فرصت تبدیل کنید',about:'آیان تراز از سال ۱۳۹۰ با تیمی از متخصصان مجرب، خدمات مشاوره مالیاتی و حسابداری ارائه می‌دهد.',phone:'۰۲۱-۱۲۳۴۵۶۷۸',email:'info@ayantaraz.ir'});
  const[editKey,setEditKey]=useState<string|null>(null);const[editVal,setEditVal]=useState('');
  const timer=useRef<any>(null);
  const show=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2500)};
  const debounceSave=useCallback((k:string,v:string)=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{setTxts(p=>({...p,[k]:v}));setEditKey(null);show('ذخیره شد ✅')},600)},[]);

  useEffect(()=>{if(tab==='dashboard')ldDash();else if(tab==='users')ldUsers();else if(tab==='audit')ldLogs()},[tab]);
  const ldDash=async()=>{setLoad(true);try{const[s,a]=await Promise.all([adminApi.getDashboardStats(),adminApi.getRecentActivity(5)]);setStats(s.data);setAct(a.data)}catch{}finally{setLoad(false)}};
  const ldUsers=async(p=1)=>{setLoad(true);try{const r=await adminApi.getUsers(p,15,q);setUsers(r.data);setUp(p)}catch{}finally{setLoad(false)}};
  const ldLogs=async(p=1)=>{setLoad(true);try{const r=await adminApi.getAuditLogs({page:p,limit:15});setLogs(r.data);setAp(p)}catch{}finally{setLoad(false)}};
  const tabs=[{id:'dashboard'as Tab,label:'داشبورد',icon:'📊'},{id:'users'as Tab,label:'کاربران',icon:'👥'},{id:'content'as Tab,label:'ویرایش محتوا',icon:'✏️'},{id:'audit'as Tab,label:'گزارش‌ها',icon:'📋'}];

  if(load&&!stats&&!users&&!logs)return<div style={{minHeight:'100vh',background:'var(--brand-black)',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{width:40,height:40,border:'3px solid var(--border-subtle)',borderTopColor:'var(--brand-gold)',borderRadius:'50%',animation:'spin .8s linear infinite'}}/></div>;

  return<div style={{minHeight:'100vh',background:'var(--brand-black)'}}>
    <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
    <header style={{borderBottom:'1px solid var(--border-subtle)',background:'var(--brand-black-soft)',padding:'0 20px'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',height:60}}><div style={{display:'flex',alignItems:'center',gap:12}}><Link href="/" style={{fontWeight:800,color:'var(--brand-gold)'}}>آیان تراز</Link><span style={{color:'var(--border-default)'}}>|</span><span style={{fontWeight:600,fontSize:'0.9375rem'}}>پنل مدیریت</span></div><Link href="/" style={{color:'var(--text-muted)',fontSize:'0.8125rem'}}>خروج</Link></div></header>
    <div className="container" style={{paddingTop:28,paddingBottom:60}}>
      {toast&&<div className="toast">{toast}</div>}
      <div style={{display:'flex',gap:2,marginBottom:28,borderBottom:'1px solid var(--border-subtle)',overflowX:'auto'}}>{tabs.map(t=><button key={t.id} onClick={()=>setTab(t.id)} style={{padding:'12px 24px',fontSize:'0.875rem',fontWeight:600,border:'none',background:'none',color:tab===t.id?'var(--brand-gold)':'var(--text-muted)',borderBottom:tab===t.id?'2px solid var(--brand-gold)':'2px solid transparent',cursor:'pointer',fontFamily:'Vazirmatn',whiteSpace:'nowrap'}}>{t.icon} {t.label}</button>)}</div>

      {tab==='dashboard'&&stats&&<div style={{display:'flex',flexDirection:'column',gap:28}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(170px,1fr))',gap:14}}>{[{l:'کاربران',v:stats.totalUsers,c:'#3b82f6'},{l:'قوانین',v:stats.totalTaxRules,c:'var(--brand-gold)'},{l:'رزروها',v:stats.totalBookings,c:'#a855f7'},{l:'منتظر',v:stats.pendingBookings,c:'#eab308'},{l:'تأیید',v:stats.confirmedBookings,c:'#22c55e'},{l:'سوالات',v:stats.totalQuestions,c:'#06b6d4'}].map((c,i)=><div key={i} className="card" style={{borderLeft:`3px solid ${c.c}`}}><div style={{fontSize:'0.8125rem',color:'var(--text-muted)',marginBottom:8}}>{c.l}</div><div style={{fontSize:'1.75rem',fontWeight:800,color:c.c}}>{c.v??'-'}</div></div>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:20}}><div className="card"><h3 style={{fontWeight:700,marginBottom:16}}>کاربران جدید</h3>{act?.recentUsers?.map((u:any)=><div key={u.id} style={{display:'flex',justifyContent:'space-between',padding:'10px 0',borderBottom:'1px solid var(--border-subtle)'}}><div><div style={{fontWeight:600}}>{u.firstName||u.lastName?`${u.firstName||''} ${u.lastName||''}`:'بدون نام'}</div><div style={{fontSize:'0.8125rem',color:'var(--text-muted)'}} dir="ltr">{u.phone}</div></div><div style={{fontSize:'0.75rem',color:'var(--text-muted)'}}>{new Date(u.createdAt).toLocaleDateString('fa-IR')}</div></div>)}</div><div className="card"><h3 style={{fontWeight:700,marginBottom:16}}>رزروهای اخیر</h3>{act?.recentBookings?.map((b:any)=><div key={b.id} style={{display:'flex',justifyContent:'space-between',padding:'10px 0',borderBottom:'1px solid var(--border-subtle)'}}><div><div style={{fontWeight:600}}>{b.service?.name||'مشاوره'}</div><div style={{fontSize:'0.8125rem',color:'var(--text-muted)'}}>{b.user?.firstName} {b.user?.lastName}</div></div><span className={`badge ${b.status==='CONFIRMED'?'badge-success':b.status==='PENDING'?'badge-warning':'badge-error'}`}>{b.status==='CONFIRMED'?'تأیید':b.status==='PENDING'?'منتظر':b.status}</span></div>)}</div></div></div>}

      {tab==='content'&&<div style={{maxWidth:700}}><h3 style={{fontWeight:700,fontSize:'1.125rem',marginBottom:16}}>ویرایش متن‌های سایت</h3><div style={{display:'flex',flexDirection:'column',gap:14}}>{Object.entries(txts).map(([k,v])=><div key={k} className="glass-card" style={{display:'flex',flexDirection:'column',gap:10}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:'0.8125rem',color:'var(--text-muted)',fontWeight:600}}>{k}</span>{editKey!==k&&<button onClick={()=>{setEditKey(k);setEditVal(v)}} style={{background:'none',border:'1px solid var(--border-subtle)',color:'var(--brand-gold)',padding:'6px 14px',borderRadius:6,cursor:'pointer',fontFamily:'Vazirmatn',fontSize:'0.8125rem'}}>✏️ ویرایش</button>}</div>{editKey===k?<><div>{v.length>60?<textarea value={editVal} onChange={e=>{setEditVal(e.target.value);debounceSave(k,e.target.value)}} rows={3} style={{...is,resize:'vertical',minHeight:80}}/>:<input value={editVal} onChange={e=>{setEditVal(e.target.value);debounceSave(k,e.target.value)}} style={is}/>}</div><div style={{display:'flex',gap:8}}><button onClick={()=>{setTxts(p=>({...p,[k]:editVal}));setEditKey(null);show('ذخیره شد ✅')}} className="btn btn-primary" style={{fontSize:'0.8125rem',padding:'8px 16px'}}>ذخیره</button><button onClick={()=>setEditKey(null)} className="btn btn-ghost" style={{fontSize:'0.8125rem',padding:'8px 16px'}}>انصراف</button></div><div style={{padding:'10px 14px',background:'rgba(198,169,98,.06)',borderRadius:8,border:'1px solid var(--border-subtle)',fontSize:'0.875rem',color:'var(--brand-gold)'}}>🔍 پیش‌نمایش: {editVal}</div></>:<div style={{padding:'10px 14px',background:'rgba(255,255,255,.02)',borderRadius:8,fontSize:'0.9375rem',color:'var(--text-secondary)'}}>{v}</div>}</div>)}</div></div>}

      {tab==='users'&&<div><div style={{display:'flex',gap:10,marginBottom:20}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ldUsers(1)} placeholder="جستجوی کاربر..." style={{...is,flex:1}}/><button onClick={()=>ldUsers(1)} className="btn btn-primary" style={{fontSize:'0.8125rem',padding:'10px 18px'}}>جستجو</button></div><Card><Table headers={['نام','شماره','نقش','وضعیت','تأیید','تاریخ']} rows={users?.data?.map(u=>({c:[u.firstName||u.lastName?`${u.firstName||''} ${u.lastName||''}`:'---',u.phone,<span className={`badge ${u.role==='SUPER_ADMIN'?'badge-error':u.role==='ADMIN'?'badge-gold':'badge-success'}`}>{u.role==='SUPER_ADMIN'?'سوپر':u.role==='ADMIN'?'ادمین':'کاربر'}</span>,<span style={{fontSize:'0.8125rem',color:u.isActive?'#22c55e':'#ef4444'}}>{u.isActive?'فعال':'غیرفعال'}</span>,u.phoneVerified?'✅':'⏳',new Date(u.createdAt).toLocaleDateString('fa-IR')]}))||[]}/>{users&&users.total>15&&<div style={{display:'flex',justifyContent:'space-between',padding:'12px 16px',borderTop:'1px solid var(--border-subtle)',fontSize:'0.8125rem',color:'var(--text-muted)'}}><span>صفحه {up}</span><div style={{display:'flex',gap:6}}><Btn onClick={()=>ldUsers(up-1)} disabled={up<=1}>قبلی</Btn><Btn onClick={()=>ldUsers(up+1)} disabled={up*15>=users.total}>بعدی</Btn></div></div>}</Card></div>}

      {tab==='audit'&&<Card><Table headers={['کاربر','عملیات','نوع','تاریخ']} rows={logs?.data?.map(l=>({c:[l.user?.firstName+' '+l.user?.lastName,<span className="badge badge-gold">{l.action}</span>,l.entityType,new Date(l.createdAt).toLocaleString('fa-IR')]}))||[]}/>{logs&&logs.total>15&&<div style={{display:'flex',justifyContent:'space-between',padding:'12px 16px',borderTop:'1px solid var(--border-subtle)',fontSize:'0.8125rem',color:'var(--text-muted)'}}><span>صفحه {ap}</span><div style={{display:'flex',gap:6}}><Btn onClick={()=>ldLogs(ap-1)} disabled={ap<=1}>قبلی</Btn><Btn onClick={()=>ldLogs(ap+1)} disabled={ap*15>=logs.total}>بعدی</Btn></div></div>}</Card>}
    </div>
  </div>;
}

function Card({children,style}:any){return<div className="card" style={{padding:0,overflow:'hidden',...style}}>{children}</div>}
function Table({headers,rows}:any){return<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr style={{borderBottom:'1px solid var(--border-subtle)'}}>{headers.map((h:string)=><th key={h} style={{textAlign:'right',padding:'12px 16px',fontSize:'0.75rem',color:'var(--text-muted)',fontWeight:600}}>{h}</th>)}</tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={i} style={{borderBottom:'1px solid var(--border-subtle)'}}>{r.c.map((c:any,j:number)=><td key={j} style={{padding:'10px 16px',fontSize:'0.875rem'}}>{c}</td>)}</tr>)}</tbody></table></div>}
function Btn({onClick,disabled,children}:any){return<button onClick={onClick} disabled={disabled} style={{padding:'6px 12px',background:'var(--surface-card)',border:'1px solid var(--border-subtle)',borderRadius:6,color:'var(--text-secondary)',cursor:disabled?'default':'pointer',fontFamily:'Vazirmatn',fontSize:'0.8125rem',opacity:disabled?.5:1}}>{children}</button>}

const is:React.CSSProperties={width:'100%',padding:'10px 14px',background:'rgba(255,255,255,.04)',border:'1.5px solid var(--border-subtle)',borderRadius:8,color:'var(--text-primary)',fontFamily:'Vazirmatn',fontSize:'0.9375rem',outline:'none'};
