#!/bin/bash
set -euo pipefail

APP_DIR=${APP_DIR:-$(pwd)}
SERVER_IP=${SERVER_IP:-202.133.91.13}
DOMAIN=${DOMAIN:-}
POSTGRES_USER=${POSTGRES_USER:-ayan_user}
POSTGRES_DB=${POSTGRES_DB:-ayan_taraz}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-$(openssl rand -base64 36 | tr -d '\n')}
JWT_SECRET=${JWT_SECRET:-$(openssl rand -hex 48)}
SEED_SUPER_ADMIN_PHONES=${SEED_SUPER_ADMIN_PHONES:-}
PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-http://${DOMAIN:-$SERVER_IP}}
CORS_ORIGINS=${CORS_ORIGINS:-$PUBLIC_BASE_URL,http://$SERVER_IP}

cd "$APP_DIR"
cat > .env <<ENV
NODE_ENV=production
PORT=4000
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?schema=public
REDIS_URL=redis://redis:6379
JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=86400
CORS_ORIGINS=$CORS_ORIGINS
NEXT_PUBLIC_API_URL=
NEXT_PUBLIC_BASE_URL=$PUBLIC_BASE_URL
PUBLIC_BASE_URL=$PUBLIC_BASE_URL
SEED_SUPER_ADMIN_PHONES=$SEED_SUPER_ADMIN_PHONES
SMS_API_KEY=PUT_YOUR_SMS_API_KEY_HERE
SMS_SENDER=PUT_YOUR_SMS_SENDER_HERE
ENV
chmod 600 .env

echo "✅ .env ساخته شد: $APP_DIR/.env"
echo "🔑 فقط مقدارهای SMS_API_KEY/SMS_SENDER و در صورت نیاز SEED_SUPER_ADMIN_PHONES را ویرایش کنید."
echo "🚀 سپس اجرا کنید: ./deploy.sh"
echo "🌐 فعلاً روی $PUBLIC_BASE_URL بالا می‌آید. بعد از آماده شدن دامنه: DOMAIN=example.com ./scripts/setup-vps.sh و سپس ./deploy.sh"
